### ISSUE TITLE
some included .h and .cpp files are missing

### ISSUE THREAD

**Issue by xbigot** [kartikkumar/emtg#2]
I ran this program, specifically PSBI_Donald, in visual studio 2017, and I found some files missing, e.g., Lambert.h, f2c.h, SpiceUsr.h, I guess these files are proprietary, could you please share them? thank you so much @kartikkumar

**Comment by kartikkumar** [comment]
@xbit126 I'm a bit snowed under with work at the moment, so I'll only be able to take a look in a couple of weeks.

The files you're referencing aren't proprietary though. 

`f2c.h` is a standard header: https://www.google.com/search?hl=en&q=f2c.h

`SpiceUsr.h` belongs to the SPICE libraray: https://naif.jpl.nasa.gov/naif/

Hope that gets you started with resolving the issues. I'll check back in a couple of weeks if you haven't managed to solve it, so I can dig a little deeper.

PS: EMTG is not actually my code: I'm mirroring it on Github. It's a NASA toolbox and this is the homepage: https://opensource.gsfc.nasa.gov/projects/emtg/index.php

**Comment by xbigot** [comment]
thanks for your response @kartikkumar 
I got all the needed scripts and I managed to solve some trajectory optimization problems, but I didn't know how to use the MPI, specifically the EMTG_MPI, which is not defined in the codes. 
I configured the boost-MPI in my Windows PC and it worked on simple programs by typing `mpiexec -n 8 test_boost_mpi.exe` in the command window. I tried to add a line `#define EMTG_MPI` in the EMTG_v8.cpp , but I got things like:
```
PS E:\EMTG_\test\x64\Debug> mpiexec -n 6 .\test.exe
program starting
program starting
program starting
default.emtgopt
default.emtgopt
default.emtgopt
Cannot find options file: default.emtgopt
Cannot find options file: default.emtgopt
Aborting program run.
Aborting program run.
Cannot find options file: default.emtgopt
Aborting program run.
program starting
default.emtgopt
Cannot find options file: default.emtgopt
Aborting program run.
program starting
default.emtgopt
Cannot find options file: default.emtgopt
Aborting program run.
program starting
default.emtgopt
Cannot find options file: default.emtgopt
Aborting program run.
```
so I wonder how this problem could be solved.

**Comment by kartikkumar** [comment]
Doesn't look familiar to me and since I don't have a Windows machine, it's a bit hard to replicate. 

Doesn't look like the project is really being supported anymore either. At least, the project seems to have disappeared from SourceForge: `https://sourceforge.net/projects/emtg`

Can you post the test code you're trying to run? Then I can try to run it on my Mac and see if it generates the same error output.

**Comment by xbigot** [comment]
Actually I simply add a line  `#define EMTG_MPI` in the front lines of `EMTG_v8.cpp` to test the boost-MPI in this project. After successful build and compile, I got outputs like above.
I think it is the conflict between processors to read the `default.emtgopt` file that cause this problem (see `EMTG_v8.cpp`), so maybe I need to modify the codes for MPI usage.

**Comment by kartikkumar** [comment]
@xbigot not sure if you managed to figure this out. Unfortunately, I can't replicate the problem and it looks like it might be beyond the scope of the core of EMTG, since you're trying to get it to work with MPI.

I'm closing this, as the original issue of missing files was resolved.
